-- Generated by HyprMod

-- Environment
hl.env("HYPRCURSOR_THEME", "hypr_Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "20")

-- Settings
hl.config({
    cursor = {
        enable_hyprcursor = true,
        no_hardware_cursors = 2,
    },
    decoration = {
        dim_inactive = true,
        dim_strength = 0.5,
        rounding = 15,
        rounding_power = 10.0,
        shadow = {
            enabled = false,
        },
    },
    ecosystem = {
        no_update_news = false,
    },
    general = {
        border_size = 1,
        col = {
            active_border = {
                colors = {"rgba(8ff0a4ff)"},
                angle = 45,
            },
            inactive_border = "0xff000000",
        },
        extend_border_grab_area = 60,
        gaps_in = 0,
        gaps_out = 0,
        layout = "master",
    },
    gestures = {
        workspace_swipe_create_new = true,
    },
    input = {
        natural_scroll = true,
        numlock_by_default = true,
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "2560x1600@240.00Hz",
    position = "0x0",
    scale = 1.6,
    cm = "srgb",
})
